const blades = require("../data/blades");

module.exports = {
    bladesObtained: [
        "Pyra",
        "Mythra",
        "Roc",
        "Nia",
        "Dromarch",
        "Poppi α",
        "Poppi QT",
        "Poppi QTπ",
        "Brighid",
        "Aegaeon",
        "Pandoria",
        "Godfrey",
        "Wulfric",
        "Perceval",
        "Agate",
        "Gorg",
        "Boreas",
        "Dagas",
        "Kasandra",
        "Praxis",
        "Theory",
        "Perun",
        "Kora",
        "Azami",
        "Ursula",
        "Nim",
        "Sheba",
        "Vess",
        "Adenine",
        "Electra",
        "Zenobia",
        "Floren",
        "KOS-MOS",
        "Herald",
        "Dahlia",
        "T-elos",
        "Poppibuster",
        "Crossette"
    ],
    bladesMaxAffinity: [
        "Pyra",
        "Mythra",
        "Roc",
        "Poppi α",
        "Poppi QT",
        "Brighid",
        // "Aegaeon",
        // "Pandoria",
        // "Godfrey",
        // "Wulfric",
        // "Perceval",
        // "Agate",
        // "Gorg",
        // "Boreas",
        // "Dagas",
        // "Kasandra",
        // "Praxis",
        // "Theory",
        // "Perun",
        // "Kora",
        // "Azami",
        // "Ursula",
        // "Nim",
        // "Sheba",
        // "Vess",
        // "Adenine",
        // "Electra",
        // "Zenobia",
        // "Floren",
        "KOS-MOS"
        // "Herald",
        // "Dahlia",
        // "T-elos",
        // "Poppibuster",
        // "Crossette"
    ]
};
