module.exports = {
    ELEMENTS: {
        Fire: "Fire",
        Water: "Water",
        Ice: "Ice",
        Wind: "Wind",
        Earth: "Earth",
        Electric: "Electric",
        Light: "Light",
        Dark: "Dark"
    },
    ROLES: {
        Attacker: "Attacker",
        Healer: "Healer",
        Tank: "Tank"
    },
    FIELD_SKILLS: {
        Fire_Mastery: "Fire Mastery",
        Water_Mastery: "Water Mastery",
        Ice_Mastery: "Ice Mastery",
        Wind_Mastery: "Wind Mastery",
        Earth_Mastery: "Earth Mastery",
        Electric_Mastery: "Electric Mastery",
        Light_Mastery: "Light Mastery",
        Dark_Mastery: "Dark Mastery",
        Agronomy: "Agronomy",
        Botany: "Botany",
        Entomology: "Entomology",
        Forestry: "Forestry",
        Ichthyology: "Ichthyology",
        Mineralogy: "Mineralogy",
        Salvaging_Mastery: "Salvaging Mastery",
        Ancient_Wisdom: "Ancient Wisdom",
        Focus: "Focus",
        Fortitude: "Fortitude",
        Girls_Talk: "Girls' Talk",
        Keen_Eye: "Keen Eye",
        Leaping: "Leaping",
        Lockpicking: "Lockpicking",
        Nopon_Wisdom: "Nopon Wisdom",
        Superstrength: "Superstrength",
        Cooking: "Cooking",
        Miasma_Dispersal: "Miasma Dispersal"
    },
    WEAPON_CLASSES: {
        Aegis_Sword: "Aegis Sword",
        Catalyst_Scimitar: "Catalyst Scimitar",
        Twin_Rings: "Twin Rings",
        Whipsword: "Whipsword",
        Big_Bang_Edge: "Big Bang Edge",
        Dual_Scythes: "Dual Scythes",
        Drill_Shield: "Drill Shield",
        Mech_Arms: "Mech Arms",
        Variable_Saber: "Variable Saber",
        Greataxe: "Greataxe",
        Megalance: "Megalance",
        Ether_Cannon: "Ether Cannon",
        Shield_Hammer: "Shield Hammer",
        Chroma_Katana: "Chroma Katana",
        Bitball: "Bitball",
        Knuckle_Claws: "Knuckle Claws",
        Calamity_Scythe: "Calamity Scythe",
        Cobra_Bardiche: "Cobra Bardiche",
        Infinity_Fans: "Infinity Fans",
        Brilliant_Twinblades: "Brilliant Twinblades",
        Sword_Tonfa: "Sword Tonfa",
        Decimation_Cannon: "Decimation Cannon",
        Rockrending_Gauntlets: "Rockrending Gauntlets",
        Monado: "Monado",
        Knives: "Knives",
        Uchigatana: "Uchigatana",
        Dual_Swords: "Dual Swords"
    }
};
